### ISSUE TITLE
Problem parsing the bibtex file

### ISSUE THREAD

**Issue by wildbill12** [apoorvkh/paperpile-to-notion#2]
I consistently get this error about "too many commas", I have found and deleted/edited the inciting reference a few times and it just keeps happening with new references......is this just due to messy references?  any way to export the bibtex with something other than commas between the names?  Any suggestions for solution?  Thanks 

See below:

File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/bibtexparser/customization.py", line 182, in splitname
    raise InvalidName("Too many commas in the name {{{0}}}.".format(name))
bibtexparser.customization.InvalidName: Too many commas in the name {Gail Harmata, Christopher Kovach, Matthew Howard, George Richerson, John Wemmie, Brian Dlouhy}.

**Comment by apoorvkh** [comment]
Seems like that library thinks "{Gail Harmata, Christopher Kovach, Matthew Howard, George Richerson, John Wemmie, Brian Dlouhy}" is one name.

What does an example entry in your `references.bib` look like? My author list is separated by "and". For example:
```
@ARTICLE{Goyal2016-op,
title = "Making the {V} in {VQA} Matter: Elevating the Role of Image Understanding in Visual Question Answering",
author = "Goyal, Yash and Khot, Tejas and Summers-Stay, Douglas and Batra, Dhruv and Parikh, Devi",
abstract = "Problems at the intersection of vision and language are of significant importance...",
month =  dec,
year =  2016,
url = "http://arxiv.org/abs/1612.00837",
file = "Making the V in VQA Matter - Elevating the Role of Image Understanding in Visual Question Answering (Goyal 2016).pdf",
archivePrefix = "arXiv",
primaryClass = "cs.CV",
eprint = "1612.00837"
}
```

**Comment by apoorvkh** [comment]
Maybe the mistake is in your paper's metadata in Paperpile. Can you correct that? I think it should be semicolon-separated, like this.
![image](https://github.com/apoorvkh/paperpile-to-notion/assets/7005565/313b83bb-ebfe-438c-99bf-b66c24cf04f8)

**Comment by wildbill12** [comment]
the error was in the metadata in paperpile - unfortunately it seems like I have a few of these, going through now and fixing them. The auto-update function didn't fix it.  But glad we identified the issue
